=== jscraftcamp/website/static/schemas/participants.2024.json
{
	"$ref": "#/definitions/participantSchema",
	"definitions": {
		"participantSchema": {
			"type": "object",
			"properties": {
				"realName": {
					"type": "object",
					"properties": {
						"givenName": { "type": "string", "minLength": 2, "maxLength": 100 },
						"familyName": { "type": "string", "minLength": 2, "maxLength": 100 },
						"placeFamilyNameFirst": { "type": ["boolean", "null"] },
						"hideFamilyNameOnWebsite": { "type": ["boolean", "null"] }
					},
					"required": ["givenName", "familyName"],
					"additionalProperties": false
				},
				"githubAccountName": {
					"type": "string",
					"pattern": "^(?!-)(?!.*--)[A-Za-z0-9-]{1,39}(?<!-)$"
				},
				"company": {
					"anyOf": [{ "type": "string", "minLength": 2, "maxLength": 200 }, { "type": "null" }]
				},
				"when": {
					"type": "object",
					"properties": { "friday": { "type": "boolean" }, "saturday": { "type": "boolean" } },
					"required": ["friday", "saturday"],
					"additionalProperties": false
				},
				"iCanTakeNotesDuringSessions": { "type": "boolean" },
				"tags": { "type": "array", "items": { "type": "string", "minLength": 1 }, "minItems": 1 },
				"vegan": { "type": ["boolean", "null"] },
				"vegetarian": { "type": ["boolean", "null"] },
				"allergies": {
					"anyOf": [
						{ "type": "array", "items": { "type": "string", "minLength": 1 }, "minItems": 1 },
						{ "type": "null" }
					]
				},
				"whatIsMyConnectionToJavascript": { "type": "string", "minLength": 3, "maxLength": 200 },
				"whatCanIContribute": { "type": "string", "minLength": 3, "maxLength": 200 },
				"tShirtSize": {
					"anyOf": [
						{ "type": "string", "enum": ["S", "M", "L", "XL", "2XL", "3XL"] },
						{ "type": "null" }
					]
				},
				"X": {
					"anyOf": [
						{ "type": "string", "pattern": "^[a-zA-Z_]{1}[a-zA-Z0-9_]{0,14}$" },
						{ "type": "null" }
					]
				},
				"mastodon": {
					"anyOf": [{ "type": "string", "format": "uri", "minLength": 1 }, { "type": "null" }]
				},
				"linkedin": {
					"anyOf": [{ "type": "string", "format": "uri", "minLength": 1 }, { "type": "null" }]
				},
				"website": {
					"anyOf": [{ "type": "string", "format": "uri", "minLength": 1 }, { "type": "null" }]
				}
			},
			"required": [
				"realName",
				"githubAccountName",
				"when",
				"iCanTakeNotesDuringSessions",
				"tags",
				"whatIsMyConnectionToJavascript",
				"whatCanIContribute",
				"tShirtSize"
			],
			"additionalProperties": false
		}
	},
	"$schema": "http://json-schema.org/draft-07/schema#"
}

=== jscraftcamp/website/participants/bastian_gebhardt.json
{
	"realName": {
		"givenName": "Bastian",
		"familyName": "Gebhardt",
		"placeFamilyNameFirst": false,
		"hideFamilyNameOnWebsite": false
	},
	"githubAccountName": "BuZZ-T",
	"company": "jambit GmbH",
	"when": {
		"friday": false,
		"saturday": true
	},
	"iCanTakeNotesDuringSessions": false,
	"tags": ["Angular", "React", "Typescript", "Core Web Vitals"],
	"vegan": false,
	"vegetarian": false,
	"allergies": [],
	"whatIsMyConnectionToJavascript": "daily business (work and private projects)",
	"whatCanIContribute": "Sharing some knowledge about stuff i've done, dunno what in particular",
	"tShirtSize": "M",
	"linkedin": "https://www.linkedin.com/in/bastian-gebhardt-9a9719301/",
	"X": "BuZZ_Tee"
}

=== jscraftcamp/website/participants/sergej-paris.json
{
	"realName": {
		"givenName": "Sergej",
		"familyName": "Paris"
	},
	"githubAccountName": "HeeL",
	"when": {
		"friday": true,
		"saturday": true
	},
	"iCanTakeNotesDuringSessions": true,
	"tags": ["TypeScript", "Big Data", "AI"],
	"vegan": false,
	"vegetarian": false,
	"whatIsMyConnectionToJavascript": "Building frontend apps and backend services using JS/TS for many years now",
	"whatCanIContribute": "Tech talks on different topics, share our experience on building things, or moderate discussions",
	"tShirtSize": "L"
}

=== jscraftcamp/website/participants/tamara.json
{
	"realName": {
		"givenName": "Tamara",
		"familyName": "Bogantseva"
	},
	"githubAccountName": "TamaraBogantseva",
	"company": "compose.us",
	"when": {
		"friday": true,
		"saturday": true
	},
	"iCanTakeNotesDuringSessions": true,
	"tags": ["Flottform.io", "Svelte", "TypeScript", "UI/UX"],
	"vegan": false,
	"vegetarian": false,
	"whatIsMyConnectionToJavascript": "Working with JavaScript",
	"whatCanIContribute": "Ready to talk about flottform.io",
	"tShirtSize": "M",
	"linkedin": "https://www.linkedin.com/in/tamara-bogantseva/",
	"X": "tamarabogant"
}

=== jscraftcamp/website/participants/johannes_ismair.json
{
	"realName": {
		"givenName": "Johannes",
		"familyName": "Ismair",
		"placeFamilyNameFirst": false,
		"hideFamilyNameOnWebsite": false
	},
	"githubAccountName": "osterbaer",
	"company": "MaibornWolff GmbH",
	"when": {
		"friday": true,
		"saturday": true
	},
	"iCanTakeNotesDuringSessions": false,
	"tags": ["TypeScript", "Next", "SolidJS", "Astro", "Accessibility", "UX", "Meta frameworks"],
	"vegan": true,
	"vegetarian": false,
	"allergies": [],
	"whatIsMyConnectionToJavascript": "Daily work",
	"whatCanIContribute": "Session about Accessibility",
	"tShirtSize": "L",
	"linkedin": "https://www.linkedin.com/in/joismair/"
}

=== jscraftcamp/website/participants/christoph.json
{
	"realName": {
		"givenName": "Christoph",
		"familyName": "Menzel",
		"placeFamilyNameFirst": false,
		"hideFamilyNameOnWebsite": false
	},
	"githubAccountName": "traveling-developer",
	"company": "inovex",
	"when": {
		"friday": true,
		"saturday": true
	},
	"iCanTakeNotesDuringSessions": false,
	"tags": ["Security", "CleanCode", "Dart"],
	"vegan": false,
	"vegetarian": false,
	"allergies": [],
	"whatIsMyConnectionToJavascript": "In the software development business for years.",
	"whatCanIContribute": "Sessions about Dart & OWASP Dependency Track",
	"tShirtSize": "S",
	"mastodon": "https://mastodon.social/@traveling_developer",
	"linkedin": "https://www.linkedin.com/in/christoph-menzel/",
	"X": "menzel42"
}

=== jscraftcamp/website/participants/abdolah_keshtkar.json
{
	"realName": {
		"givenName": "Abdolah",
		"familyName": "Keshtkar",
		"placeFamilyNameFirst": false,
		"hideFamilyNameOnWebsite": false
	},
	"githubAccountName": "HamadTheIronside",
	"company": "Predium",
	"when": {
		"friday": true,
		"saturday": true
	},
	"iCanTakeNotesDuringSessions": false,
	"tags": ["TypeScript", "JavaScript", "React"],
	"vegan": false,
	"vegetarian": false,
	"whatIsMyConnectionToJavascript": "I used to hate JavaScript, now I hate it more.",
	"whatCanIContribute": "I am pretty good at TypeScript and React, I can help with that.",
	"tShirtSize": "2XL",
	"linkedin": "https://www.linkedin.com/in/abdollah-keshtkar/",
	"website": "https://theironside.io/"
}

=== jscraftcamp/website/participants/johannes.json
{
	"realName": {
		"givenName": "Johannes",
		"familyName": "Loher",
		"placeFamilyNameFirst": false,
		"hideFamilyNameOnWebsite": false
	},
	"githubAccountName": "ghost91-",
	"company": "TNG Technology Consulting GmbH",
	"when": {
		"friday": true,
		"saturday": true
	},
	"iCanTakeNotesDuringSessions": true,
	"tags": ["TypeScript", "React", "Next.js", "SolidJS", "Node.js", "AI", "Ollama", "CSS", "Modern Web APIs"],
	"vegan": false,
	"vegetarian": false,
	"allergies": ["Mushrooms", "Fish", "Seafood"],
	"whatIsMyConnectionToJavascript": "Using it every day, both professionally and as a hobby",
	"whatCanIContribute": "Deep TypeScript Knowledge",
	"tShirtSize": "M",
	"linkedin": "https://de.linkedin.com/in/johannes-loher-062809191",
	"X": "loherj",
	"website": "https://www.johannesloher.com/"
}

=== jscraftcamp/website/participants/marvinh.json
{
	"realName": {
		"givenName": "Marvin",
		"familyName": "Hagemeister",
		"placeFamilyNameFirst": false,
		"hideFamilyNameOnWebsite": false
	},
	"githubAccountName": "marvinhagemeister",
	"company": "Deno",
	"when": {
		"friday": true,
		"saturday": true
	},
	"iCanTakeNotesDuringSessions": false,
	"tags": ["Deno", "Fresh", "TypeScript", "Rust", "Web APIs", "Preact"],
	"vegan": false,
	"vegetarian": false,
	"whatIsMyConnectionToJavascript": "Working at Deno and on Preact",
	"whatCanIContribute": "Can share stories about working on Preact, code golfing, optimizing JS tools, Signals, etc",
	"tShirtSize": "M",
	"mastodon": "https://infosec.exchange/@marvinh",
	"linkedin": "https://de.linkedin.com/in/marvin-hagemeister-53758b204",
	"X": "marvinhagemeist",
	"website": "https://marvinh.dev/"
}
