=== jscraftcamp/website/static/schemas/participants.2024.json
{
	"$ref": "#/definitions/participantSchema",
	"definitions": {
		"participantSchema": {
			"type": "object",
			"properties": {
				"realName": {
					"type": "object",
					"properties": {
						"givenName": { "type": "string", "minLength": 2, "maxLength": 100 },
						"familyName": { "type": "string", "minLength": 2, "maxLength": 100 },
						"placeFamilyNameFirst": { "type": ["boolean", "null"] },
						"hideFamilyNameOnWebsite": { "type": ["boolean", "null"] }
					},
					"required": ["givenName", "familyName"],
					"additionalProperties": false
				},
				"githubAccountName": {
					"type": "string",
					"pattern": "^(?!-)(?!.*--)[A-Za-z0-9-]{1,39}(?<!-)$"
				},
				"company": {
					"anyOf": [{ "type": "string", "minLength": 2, "maxLength": 200 }, { "type": "null" }]
				},
				"when": {
					"type": "object",
					"properties": { "friday": { "type": "boolean" }, "saturday": { "type": "boolean" } },
					"required": ["friday", "saturday"],
					"additionalProperties": false
				},
				"iCanTakeNotesDuringSessions": { "type": "boolean" },
				"tags": { "type": "array", "items": { "type": "string", "minLength": 1 }, "minItems": 1 },
				"vegan": { "type": ["boolean", "null"] },
				"vegetarian": { "type": ["boolean", "null"] },
				"allergies": {
					"anyOf": [
						{ "type": "array", "items": { "type": "string", "minLength": 1 }, "minItems": 1 },
						{ "type": "null" }
					]
				},
				"whatIsMyConnectionToJavascript": { "type": "string", "minLength": 3, "maxLength": 200 },
				"whatCanIContribute": { "type": "string", "minLength": 3, "maxLength": 200 },
				"tShirtSize": {
					"anyOf": [
						{ "type": "string", "enum": ["S", "M", "L", "XL", "2XL", "3XL"] },
						{ "type": "null" }
					]
				},
				"X": {
					"anyOf": [
						{ "type": "string", "pattern": "^[a-zA-Z_]{1}[a-zA-Z0-9_]{0,14}$" },
						{ "type": "null" }
					]
				},
				"mastodon": {
					"anyOf": [{ "type": "string", "format": "uri", "minLength": 1 }, { "type": "null" }]
				},
				"linkedin": {
					"anyOf": [{ "type": "string", "format": "uri", "minLength": 1 }, { "type": "null" }]
				},
				"website": {
					"anyOf": [{ "type": "string", "format": "uri", "minLength": 1 }, { "type": "null" }]
				}
			},
			"required": [
				"realName",
				"githubAccountName",
				"when",
				"iCanTakeNotesDuringSessions",
				"tags",
				"whatIsMyConnectionToJavascript",
				"whatCanIContribute",
				"tShirtSize"
			],
			"additionalProperties": false
		}
	},
	"$schema": "http://json-schema.org/draft-07/schema#"
}

=== jscraftcamp/website/participants/florian_rappl.json
{
	"realName": {
		"givenName": "Florian",
		"familyName": "Rappl",
		"placeFamilyNameFirst": false,
		"hideFamilyNameOnWebsite": false
	},
	"githubAccountName": "FlorianRappl",
	"company": "smapiot",
	"when": {
		"friday": true,
		"saturday": true
	},
	"iCanTakeNotesDuringSessions": false,
	"tags": ["React", "Microfrontends", "Architecture", "TypeScript", "Zustand", "esbuild"],
	"vegan": false,
	"vegetarian": false,
	"allergies": [],
	"whatIsMyConnectionToJavascript": "Pretty much the son of the father of JavaScript. One could say we are brothers.",
	"whatCanIContribute": "Anything from JS or TS internals up to large-scale webapp architecture.",
	"tShirtSize": "L",
	"linkedin": "https://www.linkedin.com/in/florian-rappl/",
	"X": "FlorianRappl",
	"website": "https://www.florian-rappl.de"
}

=== jscraftcamp/website/participants/jfhr.json
{
	"realName": {
		"givenName": "Jakob",
		"familyName": "Fahr",
		"placeFamilyNameFirst": false,
		"hideFamilyNameOnWebsite": false
	},
	"githubAccountName": "jfhr",
	"company": "InsiderPie",
	"when": {
		"friday": true,
		"saturday": true
	},
	"iCanTakeNotesDuringSessions": true,
	"tags": ["Node.js", "Web Scraping", "Web Security", "PostgreSQL"],
	"vegan": true,
	"vegetarian": true,
	"allergies": [],
	"tShirtSize": "S",
	"whatIsMyConnectionToJavascript": "Not a day goes by where I don't use JavaScript.",
	"whatCanIContribute": "I can share my experience developing and running numerous node.js web services.",
	"website": "https://jfhr.de"
}

=== jscraftcamp/website/participants/patrickwire.json
{
	"realName": {
		"givenName": "Patrick",
		"familyName": "Müller"
	},
	"githubAccountName": "patrickwire",
	"company": "alm engineering",
	"when": {
		"friday": true,
		"saturday": true
	},
	"iCanTakeNotesDuringSessions": false,
	"tags": ["React", "AI", "vibecoding"],
	"whatIsMyConnectionToJavascript": "Using it forever.",
	"whatCanIContribute": "A Session or two",
	"tShirtSize": "3XL"
}

=== jscraftcamp/website/participants/kai-kopecky.json
{
  "realName": {
    "givenName": "Kai",
    "familyName": "Kopecky",
    "placeFamilyNameFirst": false,
    "hideFamilyNameOnWebsite": true
  },
  "githubAccountName": "kkopecky",
  "company": "Saab Deutschland GmbH",
  "when": {
    "friday": true,
    "saturday": true
  },
  "iCanTakeNotesDuringSessions": false,
  "tags": ["React", "TypeScript", "Redux"],
  "vegan": false,
  "vegetarian": false,
  "allergies": [],
  "whatIsMyConnectionToJavascript": "Someone has to fix the internet",
  "whatCanIContribute": "I'm happy to share my experience",
  "tShirtSize": "3XL",
  "linkedin": "https://www.linkedin.com/in/kai-kopecky-9365b122/"
}

=== jscraftcamp/website/participants/michael_leimstaedtner.json
{
	"realName": {
		"givenName": "Michael",
		"familyName": "Leimst√§dtner",
		"placeFamilyNameFirst": false,
		"hideFamilyNameOnWebsite": false
	},
	"githubAccountName": "makmic",
	"company": "makandra",
	"when": {
		"friday": false,
		"saturday": true
	},
	"iCanTakeNotesDuringSessions": false,
	"tags": ["Rails", "Unpoly", "Web Audio API", "A11Y"],
	"whatIsMyConnectionToJavascript": "I've been writing some JS every other day for the past decade",
	"whatCanIContribute": "I might be able to answer some Unpoly question and give perspective on rather plain JS settings with server side rendering apps",
	"tShirtSize": "M",
	"linkedin": "https://www.linkedin.com/in/leimstaedtner/"
}

=== jscraftcamp/website/participants/jonathan_prince.json
{
	"realName": {
		"givenName": "Jonathan",
		"familyName": "Prince",
		"placeFamilyNameFirst": false,
		"hideFamilyNameOnWebsite": false
	},
	"githubAccountName": "JonathanPrince",
	"company": "NVISO",
	"when": {
		"friday": true,
		"saturday": true
	},
	"iCanTakeNotesDuringSessions": true,
	"tags": ["JS", "Security", "Mainframes", "AS400"],
	"vegan": false,
	"vegetarian": false,
	"allergies": [],
	"whatIsMyConnectionToJavascript": "JavaScript was my first love...",
	"whatCanIContribute": "Something about security, mainframes, or smart contracts?",
	"tShirtSize": "L",
	"linkedin": "https://www.linkedin.com/in/jonathan-m-prince/",
	"X": "greatsage",
	"website": "https://edgeofconfusion.com"
}

=== jscraftcamp/website/participants/lukastaegert.json
{
	"realName": {
		"givenName": "Lukas",
		"familyName": "Taegert-Atkinson",
		"placeFamilyNameFirst": false,
		"hideFamilyNameOnWebsite": false
	},
	"githubAccountName": "lukastaegert",
	"company": "TNG Technology Consulting",
	"when": {
		"friday": true,
		"saturday": false
	},
	"iCanTakeNotesDuringSessions": false,
	"tags": ["GraphQL", "Rust", "Workers", "Bundling"],
	"vegan": false,
	"vegetarian": true,
	"allergies": [],
	"whatIsMyConnectionToJavascript": "I love hacking things as well as deeply understanding them, which made me maintainer of RollupJS since 2017. Since then, there are few things in the language I did not touch yet.",
	"whatCanIContribute": "Experiences from integrating native Rust code in JavaScript, possibly something about schema stitching in GraphQL.",
	"tShirtSize": "M",
	"mastodon": "https://m.webtoo.ls/@lukastaegert",
	"website": "https://rollupjs.org"
}

=== jscraftcamp/website/participants/gustaf.json
{
  "realName": {
    "givenName": "Gustaf",
    "familyName": "Graf",
    "placeFamilyNameFirst": false,
    "hideFamilyNameOnWebsite": false
  },
  "githubAccountName": "gggscript",
  "company": "onyo",
  "when": {
    "friday": true,
    "saturday": false
  },
  "iCanTakeNotesDuringSessions": false,
  "tags": [
    "Thinking better on purpose",
    "Reducing existential risk",
    "Rabbit holing"
  ],
  "vegan": true,
  "vegetarian": true,
  "allergies": [],
  "whatIsMyConnectionToJavascript": "7 years of programming, the last 2 of which were at my job",
  "whatCanIContribute": "You tell me about your niche interest ü§ù I try to understand as deeply as possible & ask something useful",
  "tShirtSize": "S"
}
