=== jscraftcamp/website/static/schemas/participants.2024.json
{
	"$ref": "#/definitions/participantSchema",
	"definitions": {
		"participantSchema": {
			"type": "object",
			"properties": {
				"realName": {
					"type": "object",
					"properties": {
						"givenName": { "type": "string", "minLength": 2, "maxLength": 100 },
						"familyName": { "type": "string", "minLength": 2, "maxLength": 100 },
						"placeFamilyNameFirst": { "type": ["boolean", "null"] },
						"hideFamilyNameOnWebsite": { "type": ["boolean", "null"] }
					},
					"required": ["givenName", "familyName"],
					"additionalProperties": false
				},
				"githubAccountName": {
					"type": "string",
					"pattern": "^(?!-)(?!.*--)[A-Za-z0-9-]{1,39}(?<!-)$"
				},
				"company": {
					"anyOf": [{ "type": "string", "minLength": 2, "maxLength": 200 }, { "type": "null" }]
				},
				"when": {
					"type": "object",
					"properties": { "friday": { "type": "boolean" }, "saturday": { "type": "boolean" } },
					"required": ["friday", "saturday"],
					"additionalProperties": false
				},
				"iCanTakeNotesDuringSessions": { "type": "boolean" },
				"tags": { "type": "array", "items": { "type": "string", "minLength": 1 }, "minItems": 1 },
				"vegan": { "type": ["boolean", "null"] },
				"vegetarian": { "type": ["boolean", "null"] },
				"allergies": {
					"anyOf": [
						{ "type": "array", "items": { "type": "string", "minLength": 1 }, "minItems": 1 },
						{ "type": "null" }
					]
				},
				"whatIsMyConnectionToJavascript": { "type": "string", "minLength": 3, "maxLength": 200 },
				"whatCanIContribute": { "type": "string", "minLength": 3, "maxLength": 200 },
				"tShirtSize": {
					"anyOf": [
						{ "type": "string", "enum": ["S", "M", "L", "XL", "2XL", "3XL"] },
						{ "type": "null" }
					]
				},
				"X": {
					"anyOf": [
						{ "type": "string", "pattern": "^[a-zA-Z_]{1}[a-zA-Z0-9_]{0,14}$" },
						{ "type": "null" }
					]
				},
				"mastodon": {
					"anyOf": [{ "type": "string", "format": "uri", "minLength": 1 }, { "type": "null" }]
				},
				"linkedin": {
					"anyOf": [{ "type": "string", "format": "uri", "minLength": 1 }, { "type": "null" }]
				},
				"website": {
					"anyOf": [{ "type": "string", "format": "uri", "minLength": 1 }, { "type": "null" }]
				}
			},
			"required": [
				"realName",
				"githubAccountName",
				"when",
				"iCanTakeNotesDuringSessions",
				"tags",
				"whatIsMyConnectionToJavascript",
				"whatCanIContribute",
				"tShirtSize"
			],
			"additionalProperties": false
		}
	},
	"$schema": "http://json-schema.org/draft-07/schema#"
}

=== jscraftcamp/website/participants/ivan_vasilev.json
{
	"realName": {
		"givenName": "Ivan",
		"familyName": "Vasilev",
		"placeFamilyNameFirst": false,
		"hideFamilyNameOnWebsite": false
	},
	"githubAccountName": "konclave",
	"company": "Satellytes",
	"when": {
		"friday": true,
		"saturday": true
	},
	"iCanTakeNotesDuringSessions": false,
	"tags": ["Typescript", "React", "Zustand", "Microfrontends"],
	"vegan": false,
	"vegetarian": false,
	"allergies": [],
	"whatIsMyConnectionToJavascript": "It's the my main programming language for more than 10 years.",
	"whatCanIContribute": "Creating React applications, basics of accessibility",	
  "tShirtSize": "L",
	"linkedin": "https://www.linkedin.com/in/konclave/"
}

=== jscraftcamp/website/participants/georgiee.json
{
  "realName": {
    "givenName": "Georgios",
    "familyName": "Kaleadis",
    "placeFamilyNameFirst": false,
    "hideFamilyNameOnWebsite": false
  },
  "githubAccountName": "georgiee",
  "company": "Satellytes",
  "when": {
    "friday": true,
    "saturday": true
  },
  "iCanTakeNotesDuringSessions": false,
  "tags": ["Angular", "React", "Accessibility", "Code Reviews", "Inner Source", "Ruby on Rails"],
  "whatIsMyConnectionToJavascript": "Flash ignited my tech passion in 1999, leading me to a Frontend career and to the founding of Satellytes six years ago.",
  "whatCanIContribute": "Working with modern tech in clumsy enterprises is challenging but highly rewarding. I may share some stories around it.",
  "tShirtSize": "L",
  "linkedin": "https://www.linkedin.com/in/kaleadis/",
  "website": "https://www.satellytes.com"
}

=== jscraftcamp/website/participants/mohammed_faour.json
{
	"realName": {
		"givenName": "Mohammed",
		"familyName": "Faour",
		"placeFamilyNameFirst": false,
		"hideFamilyNameOnWebsite": false
	},
	"githubAccountName": "mfaour34",
	"company": "FINN GmbH",
	"when": {
		"friday": true,
		"saturday": false
	},
	"iCanTakeNotesDuringSessions": false,
	"tags": ["Node", "Typescript", "Serverless"],
	"vegan": false,
	"vegetarian": true,
	"allergies": [],
	"whatIsMyConnectionToJavascript": "daily business (work and private projects)",
	"whatCanIContribute": "Sharing some knowledge about stuff i've done",
	"tShirtSize": "L",
	"linkedin": "https://www.linkedin.com/in/mohammed-faour-6167451b0/"
}

=== jscraftcamp/website/participants/dejanr.json
{
  "realName": {
    "givenName": "Dejan",
    "familyName": "Ranisavljevic",
    "placeFamilyNameFirst": false,
    "hideFamilyNameOnWebsite": false
  },
  "githubAccountName": "dejanr",
  "company": "futurice",
  "when": {
    "friday": false,
    "saturday": true
  },
  "iCanTakeNotesDuringSessions": true,
  "tags": [
    "Software Architecture",
    "Software Quality",
    "Software Craftsmanship",
    "Functional Programming",
    "Development Environments"
  ],
  "vegan": false,
  "vegetarian": false,
  "whatIsMyConnectionToJavascript": "As a full stack developer, i use it on both ends frontend and backend.",
  "whatCanIContribute": "Experienced in utilizing Pulumi for IaC, generative AI, LLMs, and RAG applications.",
  "tShirtSize": "2XL",
  "linkedin": "https://www.linkedin.com/in/dejanr/",
  "X": "dejanr"
}

=== jscraftcamp/website/participants/markus_krogemann.json
{
	"realName": {
		"givenName": "Markus",
		"familyName": "Krogemann",
		"placeFamilyNameFirst": false,
		"hideFamilyNameOnWebsite": false
	},
	"githubAccountName": "mkrogemann",
	"company": "Markus Krogemann",
	"when": {
		"friday": true,
		"saturday": true
	},
	"iCanTakeNotesDuringSessions": true,
  "tags": [
    "TypeScript",
    "Tailwind CSS",
    "Astro",
    "AWS"
  ],
	"vegan": false,
	"vegetarian": false,
  "allergies": [],
	"whatIsMyConnectionToJavascript": "Mainly wanting to learn more about language, ecosystem and community",
	"whatCanIContribute": "Lots of curiosity and anecdotes on failed endeavours",
	"tShirtSize": "XL",
	"linkedin": "https://www.linkedin.com/in/mkrogemann/",
  "website": "https://just-cues.krogemann.de"
}

=== jscraftcamp/website/participants/fii.json
{
	"realName": {
		"givenName": "Stefanie",
		"familyName": "Hasler",
		"placeFamilyNameFirst": false,
		"hideFamilyNameOnWebsite": false
	},
	"githubAccountName": "haslers",
	"company": "codecentric AG",
	"when": {
		"friday": true,
		"saturday": true
	},
	"iCanTakeNotesDuringSessions": false,
	"tags": ["Typescript", "React", "Next.js", "Communication", "Performance"],
	"vegan": true,
	"vegetarian": false,
	"whatIsMyConnectionToJavascript": "I use Typescript every day, and Javascript whenever I am confronted with a library which does not have types.",
	"whatCanIContribute": "Facilitation ;), 10 years of development experience, contact, a buddy for everyone who needs one",
	"tShirtSize": "M",
	"linkedin": "https://www.linkedin.com/in/stefanie-hasler-05458a4/"
}

=== jscraftcamp/website/participants/feedm3.json
{
  "realName": {
    "givenName": "Fabian",
    "familyName": "Dietenberger",
    "placeFamilyNameFirst": false,
    "hideFamilyNameOnWebsite": false
  },
  "githubAccountName": "feedm3",
  "company": "Satellytes",
  "when": {
    "friday": true,
    "saturday": true
  },
  "iCanTakeNotesDuringSessions": false,
  "tags": ["React", "Module Federation", "Rspack", "Microfrontends", "Typescript"],
  "vegan": false,
  "vegetarian": false,
  "allergies": [],
  "whatIsMyConnectionToJavascript": "Working full stack with JS for over 10 years. Frontend, backend, infra, whatever it takes to make a great product!",
  "whatCanIContribute": "Currently working with React and Module Federation to build micro frontends at enterprise level, so happy to share experience and knowledge.",
  "tShirtSize": "M",
  "linkedin": "https://www.linkedin.com/in/fabiandietenberger/",
  "website": "https://www.satellytes.com"
}

=== jscraftcamp/website/participants/mohsinulhaq.json
{
	"realName": {
		"givenName": "Mohsin",
		"familyName": "Ul Haq",
		"placeFamilyNameFirst": false,
		"hideFamilyNameOnWebsite": false
	},
	"githubAccountName": "mohsinulhaq",
	"company": "HolidayCheck",
	"when": {
		"friday": true,
		"saturday": true
	},
	"iCanTakeNotesDuringSessions": false,
	"tags": ["TypeScript", "React", "React Native", "RTK Query"],
	"vegan": false,
	"vegetarian": false,
	"whatIsMyConnectionToJavascript": "Working on TS, React and React Native",
	"whatCanIContribute": "Can share information about working on design systems, RTK Query, etc.",
	"tShirtSize": "M",
	"linkedin": "http://linkedin.com/in/mohsinulhaq",
	"X": "mohsinulhaq"
}
