=== jscraftcamp/website/static/schemas/participants.2023.json
{
	"$ref": "#/definitions/participantSchema",
	"definitions": {
		"participantSchema": {
			"type": "object",
			"properties": {
				"name": { "type": "string", "minLength": 2 },
				"company": { "anyOf": [{ "type": "string", "minLength": 2 }, { "type": "null" }] },
				"when": {
					"type": "object",
					"properties": { "friday": { "type": "boolean" }, "saturday": { "type": "boolean" } },
					"required": ["friday", "saturday"],
					"additionalProperties": false
				},
				"iCanTakeNotesDuringSessions": { "type": "boolean" },
				"tags": { "type": "array", "items": { "type": "string" }, "minItems": 1 },
				"vegan": { "type": ["boolean", "null"] },
				"vegetarian": { "type": ["boolean", "null"] },
				"allergies": {
					"anyOf": [
						{ "type": "array", "items": { "type": "string" }, "minItems": 1 },
						{ "type": "null" }
					]
				},
				"whatIsMyConnectionToJavascript": { "type": "string", "minLength": 3, "maxLength": 200 },
				"whatCanIContribute": { "type": "string", "minLength": 3, "maxLength": 200 },
				"tShirt": {
					"anyOf": [
						{
							"type": "object",
							"properties": {
								"type": { "type": "string", "enum": ["fitted", "regular"] },
								"size": { "type": "string", "enum": ["S", "M", "L", "XL", "XXL"] }
							},
							"required": ["type", "size"],
							"additionalProperties": false
						},
						{ "type": "null" }
					]
				},
				"twitter": {
					"anyOf": [
						{ "type": "string", "pattern": "^[a-z_]{1}[a-z0-9_]{0,14}$" },
						{ "type": "null" }
					]
				},
				"mastodon": { "anyOf": [{ "type": "string", "minLength": 1 }, { "type": "null" }] }
			},
			"required": [
				"name",
				"when",
				"iCanTakeNotesDuringSessions",
				"tags",
				"whatIsMyConnectionToJavascript",
				"whatCanIContribute"
			],
			"additionalProperties": false
		}
	},
	"$schema": "http://json-schema.org/draft-07/schema#"
}

=== jscraftcamp/website/participants/friedrich.json
{
	"name": "Friedrich ten Hagen",
	"company": "Advertace",
	"when": {
		"friday": true,
		"saturday": true
	},
	"iCanTakeNotesDuringSessions": false,
	"tags": ["React", "Html", "CSS", "vanilla js"],
	"vegan": false,
	"vegetarian": true,
	"allergies": ["none"],
	"whatIsMyConnectionToJavascript": "I have been studying web dev for a year and am now getting to know React.",
	"whatCanIContribute": "Enthusiasm. Also happy to help where needed.",
	"tShirt": {
		"size": "M",
		"type": "regular"
	}
}

=== jscraftcamp/website/participants/martin_grandrath.json
{
	"name": "Martin Grandrath",
	"company": "codecentric AG",
	"when": {
		"friday": true,
		"saturday": true
	},
	"iCanTakeNotesDuringSessions": false,
	"tags": ["Agile", "TDD", "Architecture"],
	"vegan": false,
	"vegetarian": false,
	"whatIsMyConnectionToJavascript": "I'm a JS developer for over 12 years. It became my primary programming language :-)",
	"whatCanIContribute": "I like to share the 'Testing without Mocks' pattern by James Shore",
	"tShirt": {
		"size": "L",
		"type": "regular"
	}
}

=== jscraftcamp/website/participants/ana.json
{
	"name": "Ana Carraca",
	"company": "Maze",
	"when": {
		"friday": true,
		"saturday": true
	},
	"iCanTakeNotesDuringSessions": true,
	"tags": ["React", "NestJS", "GraphQL", "Next.js"],
	"vegan": false,
	"vegetarian": true,
	"whatIsMyConnectionToJavascript": "I've been working with JS/TS for a while, looking forward to learn new things",
	"whatCanIContribute": "Can talk about observability/monitoring and how to add authorization to an existing product",
	"tShirt": {
		"size": "M",
		"type": "fitted"
	},
	"twitter": "ACarraca"
}

=== jscraftcamp/website/participants/alex_munoz.json
{
    "name": "Alex Mu√±oz",
    "company": "eXXcellent solutions GmbH",
    "when": {
        "friday": true,
        "saturday": true
    },
    "iCanTakeNotesDuringSessions": false,
    "tags": ["JavaScript", "TypeScript", "React"],
    "whatIsMyConnectionToJavascript": "I use Js/Ts in my daily job",
    "whatCanIContribute": "Exchange of knowledge, ideas and experiences around Web Development.",
    "tShirt": {
        "size": "S",
        "type": "regular"
    }
}

=== jscraftcamp/website/participants/moka.json
{
	"name": "Monica Mikhael",
	"company": "FINN",
	"when": {
		"friday": true,
		"saturday": false
	},
	"iCanTakeNotesDuringSessions": false,
	"tags": ["Typescript", "React", "Next.js", "Node"],
	"vegan": false,
	"vegetarian": false,
	"whatIsMyConnectionToJavascript": "I've been working with JS/TS every day at work, looking forward to learn new things",
	"whatCanIContribute": "I am not good at talks, but I can share my experience in React and JS/TS in general",
	"tShirt": {
		"size": "L",
		"type": "fitted"
	}
}

=== jscraftcamp/website/participants/larisa.json
{
	"name": "Larisa Dolgova",
	"company": "Futurice",
	"when": {
		"friday": true,
		"saturday": true
	},
	"iCanTakeNotesDuringSessions": false,
	"tags": ["TypeScript", "React", "GraphQL", "Python"],
	"vegan": false,
	"vegetarian": false,
	"whatIsMyConnectionToJavascript": "I work with JS on a daily basis",
	"whatCanIContribute": "Participate in discussions",
	"tShirt": {
		"size": "S",
		"type": "regular"
	}
}

=== jscraftcamp/website/participants/vanderlei_silva.json
{
	"name": "Vanderlei Alves da Silva",
	"company": "Regiondo GmbH",
	"when": {
		"friday": true,
		"saturday": true
	},
	"iCanTakeNotesDuringSessions": true,
	"tags": ["Clean Code", "Clean Architecture", "ECMAScript", "Node", "typescript"],
	"vegan": false,
	"vegetarian": false,
	"whatIsMyConnectionToJavascript": "working",
	"whatCanIContribute": "Sharing knowledge around Microfrontend topics, web component development, Javascript and Typescript",
	"tShirt": {
		"size": "S",
		"type": "regular"
	}
}

=== jscraftcamp/website/participants/stefan_hoferer.json
{
  "name": "Stefan Hoferer",
  "when": {
    "friday": false,
    "saturday": true
  },
  "iCanTakeNotesDuringSessions": false,
  "tags": ["AWS SDK", "AWS Lambda", "React"],
  "vegan": false,
  "vegetarian": false,
  "whatIsMyConnectionToJavascript": "I like to work fast",
  "whatCanIContribute": "Knowledge in building serverless Apps",
  "tShirt": {
    "size": "3XL",
    "type": "regular"
  }
}
