=== jscraftcamp/website/static/schemas/participants.2023.json
{
	"$ref": "#/definitions/participantSchema",
	"definitions": {
		"participantSchema": {
			"type": "object",
			"properties": {
				"name": { "type": "string", "minLength": 2 },
				"company": { "anyOf": [{ "type": "string", "minLength": 2 }, { "type": "null" }] },
				"when": {
					"type": "object",
					"properties": { "friday": { "type": "boolean" }, "saturday": { "type": "boolean" } },
					"required": ["friday", "saturday"],
					"additionalProperties": false
				},
				"iCanTakeNotesDuringSessions": { "type": "boolean" },
				"tags": { "type": "array", "items": { "type": "string" }, "minItems": 1 },
				"vegan": { "type": ["boolean", "null"] },
				"vegetarian": { "type": ["boolean", "null"] },
				"allergies": {
					"anyOf": [
						{ "type": "array", "items": { "type": "string" }, "minItems": 1 },
						{ "type": "null" }
					]
				},
				"whatIsMyConnectionToJavascript": { "type": "string", "minLength": 3, "maxLength": 200 },
				"whatCanIContribute": { "type": "string", "minLength": 3, "maxLength": 200 },
				"tShirt": {
					"anyOf": [
						{
							"type": "object",
							"properties": {
								"type": { "type": "string", "enum": ["fitted", "regular"] },
								"size": { "type": "string", "enum": ["S", "M", "L", "XL", "XXL"] }
							},
							"required": ["type", "size"],
							"additionalProperties": false
						},
						{ "type": "null" }
					]
				},
				"twitter": {
					"anyOf": [
						{ "type": "string", "pattern": "^[a-z_]{1}[a-z0-9_]{0,14}$" },
						{ "type": "null" }
					]
				},
				"mastodon": { "anyOf": [{ "type": "string", "minLength": 1 }, { "type": "null" }] }
			},
			"required": [
				"name",
				"when",
				"iCanTakeNotesDuringSessions",
				"tags",
				"whatIsMyConnectionToJavascript",
				"whatCanIContribute"
			],
			"additionalProperties": false
		}
	},
	"$schema": "http://json-schema.org/draft-07/schema#"
}

=== jscraftcamp/website/participants/dmitrii_forofontov.json
{
    "name": "Dmitrii Forofontov",
    "when": {
        "friday": true,
        "saturday": true
    },
    "iCanTakeNotesDuringSessions": true,
    "tags": ["Next", "TS", "Clean Code", "Microservices"],
    "vegan": false,
    "vegetarian": false,
    "whatIsMyConnectionToJavascript": "Working with JS for 2.5 years, mostly on the fullstack side.",
    "whatCanIContribute": "How Typescript makes code harder to read and maintain and how to avoid it.",
    "tShirt": {
        "size": "L",
        "type": "regular"
    }
}
